mumu:
  emulators:
    - index: 0
      port: 16384
      name: "MuMu模拟器-1"
      description: "主模拟器"
    - index: 1
      port: 16416
      name: "MuMu模拟器-2"
      description: "副模拟器1"
    - index: 2
      port: 16448
      name: "MuMu模拟器-3"
      description: "副模拟器2"

  adb:
    path: "C:/Netease/MuMuPlayer-12.0/shell/adb.exe"
    connectionTimeout: 30
    commandTimeout: 10

  image:
    templateDir: "templates"
    matchThreshold: 0.8
    clickOffsetRange: 10

  behavior:
    checkInterval: 1000
    maxRetryCount: 3
    clickDelay: 500

user:
  username: "admin"
  password: "123456"

logging:
  level:
    com: DEBUG